# Proyecto del Día 8 - Análisis de Datos Meteorológicos

Este proyecto consiste en analizar un conjunto de datos meteorológicos utilizando Python y NumPy. 
El objetivo es aplicar las técnicas de manipulación de arrays, tratamiento de datos faltantes, 
y análisis estadístico básico en un conjunto de datos del mundo real.

## Tareas a Realizar:
1. Crear un DataFrame a partir de los datos del archivo **datos_meteorologicos.csv** provisto en esta lección.
2. Realizar observaciones iniciales de los datos con Pandas.
3. Convertir las columnas del DataFrame en arrays de NumPy.
4. Identificar los datos faltantes en los arrays, y reemplazarlos por el promedio de los valores del respectivo array.
5. Realizar análisis estadísticos básicos. Mínimamente se espera que puedas extraer la siguiente información de tus arrays:
    * La temperatura promedio
    * El total de precipitaciones
    * La máxima humedad registrada
    * La fecha más calurosa
    * La fehca más fría
6. Exportar los resultados a un nuevo archivo CSV.

¡Mucha suerte con tu proyecto!


### 1. Crear un DataFrame a partir de los datos del archivo datos_meteorologicos.csv provisto en esta lección.

In [87]:
import pandas as pd 
import numpy as np

ruta = "C:/Users/KeythiCL/Downloads/datos_meteorologicos.csv"
df = pd.read_csv(ruta)
df

Fecha  Temperatura  Precipitación    Humedad
0     01/01/2010    17.440675      10.957482  52.384637
1     02/01/2010    25.759468       5.315628  30.633530
2     03/01/2010    20.138169      15.317706  41.496715
3     04/01/2010    17.244159      13.151008  90.684704
4     05/01/2010    11.182740      16.413667  22.116422
...          ...          ...            ...        ...
5105  24/12/2023    -9.554692      12.700998  50.094533
5106  25/12/2023     2.837831       5.475686  92.456057
5107  26/12/2023    29.873597       4.615012  18.362847
5108  27/12/2023          NaN            NaN        NaN
5109  28/12/2023    37.308043       7.330510  50.646211

[5110 rows x 4 columns]

### 2. Realizar observaciones iniciales de los datos con Pandas.

In [90]:
df.head()
df.tail()
df.shape
df.columns
df.info()
df.describe()
df.isnull()
df.isnull().sum()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5110 entries, 0 to 5109
Data columns (total 4 columns):
 #   Column         Non-Null Count  Dtype  
---  ------         --------------  -----  
 0   Fecha          5110 non-null   object 
 1   Temperatura    4855 non-null   float64
 2   Precipitación  4855 non-null   float64
 3   Humedad        4855 non-null   float64
dtypes: float64(3), object(1)
memory usage: 159.8+ KB


Fecha              0
Temperatura      255
Precipitación    255
Humedad          255
dtype: int64

### 3. Convertir las columnas del DataFrame en arrays de NumPy.

In [93]:
temperatura = df['Temperatura'].to_numpy()
precipitacion = df['Precipitación'].to_numpy()
humedad = df['Humedad'].to_numpy()

temperatura

array([17.4406752 , 25.75946832, 20.1381688 , ..., 29.87359717,
               nan, 37.30804318])

### 4. Identificar los datos faltantes en los arrays, y reemplazarlos por el promedio de los valores del respectivo array.

In [96]:
# Identificar datos faltantes con isnan()
temp_nulo = np.isnan(temperatura)
precip_nulo = np.isnan(precipitacion)
humed_nulo = np.isnan(humedad)

temp_nulo

array([False, False, False, ..., False,  True, False])

In [101]:
# Identificar el promedio de cada array
temp_promedio = np.nanmean(temperatura)
precip_promedio = np.nanmean(precipitacion)
humed_promedio = np.nanmean(humedad)

# Reemplazar los valores nulos con el promedio del array
temperatura[temp_nulo] = temp_promedio
precipitacion[precip_nulo] = precip_promedio
humedad[humed_nulo] = humed_promedio

temperatura

array([17.4406752 , 25.75946832, 20.1381688 , ..., 29.87359717,
       14.88929572, 37.30804318])

In [113]:
# Abordaje alternativo para lograr el mismo resultado
temp_corregido = np.where(np.isnan(temperatura), temp_promedio, temperatura)
pres_corregido = np.where(np.isnan(precipitacion), precip_promedio, precipitacion)
hum_corregido = np.where(np.isnan(humedad), humed_promedio, precipitacion)
hum_corregido

array([10.957482  ,  5.31562765, 15.31770609, ...,  4.61501177,
        9.9016036 ,  7.33051023])

### 5. Realizar análisis estadísticos básicos.

##### Temperatura promedio

In [107]:
temperatura_promedio = temp_corregido.mean()
temperatura_promedio

14.889295723531713

##### Total de precipitaciones

In [111]:
total_pres = pres_corregido.sum()
total_pres

50597.19438939993

##### Máxima humedad registrada

In [117]:
humedad_max = np.max(humedad)
humedad_max

99.99658156071747

##### Fecha más calurosa

In [119]:
# Identificar la temperatura más alta
mas_calor = np.max(temperatura)
mas_calor

39.99820092713012

In [121]:
# Registro correspondiente a la temperatura más alta
registro_mas_caluroso = np.where(temperatura == mas_calor)[0][0]
registro_mas_caluroso

2749

In [123]:
# Fecha correspondiente al registro más caluroso
fecha_mas_calurosa = df.iloc[registro_mas_caluroso]['Fecha']
fecha_mas_calurosa

'12/07/2017'

In [135]:
fila_max_temp = df.loc[df['Temperatura'].idxmax()]  # Obtiene la fila con la temp. máxima
fecha_max = fila_max_temp['Fecha']  # Obtiene la fecha correspondiente

print(fecha_max)

12/07/2017


##### Fehca más fría

In [139]:
fila_fria_temp = df.loc[df['Temperatura'].idxmin()]  # Obtiene la fila con la temp. máxima
fecha_min = fila_fria_temp['Fecha']  # Obtiene la fecha correspondiente

print(fecha_min)

23/07/2020


### 6. Exportar los resultados a un nuevo archivo CSV.

In [141]:
# Crear un DataFrame con los resultados
resultados = pd.DataFrame({
    'Metrica': ['Temperatura Promedio', 'Precipitación Total', 'Humedad Máxima', 'Día Más Caluroso', 'Día Más Frío'],
    'Valor': [temperatura_promedio, total_pres , humedad_max, fecha_max, fecha_min]
})

# Guardar los resultados en un nuevo archivo CSV
resultados.to_csv('C:/Users/KeythiCL/Downloads/resultados.csv', index=False)